# Generated by Django 4.2.16 on 2026-08-26 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karsilastirma', '0009_toptanci_iskonto_kullanici'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('hazirlaniyor', 'Hazırlanıyor'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='bekliyor', max_length=20)),
                ('not_alani', models.TextField(blank=True, help_text='Kullanıcı notu')),
                ('admin_notu', models.TextField(blank=True, help_text='Admin iç notu')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparisler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='SiparisUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toptanci', models.CharField(max_length=80)),
                ('urun_adi', models.CharField(max_length=255)),
                ('marka', models.CharField(blank=True, max_length=100)),
                ('ebat', models.CharField(max_length=30)),
                ('mevsim', models.CharField(blank=True, max_length=20)),
                ('dot', models.CharField(blank=True, max_length=20)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miktar', models.PositiveSmallIntegerField(default=1)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='karsilastirma.siparis')),
            ],
            options={
                'verbose_name': 'Sipariş Ürünü',
                'verbose_name_plural': 'Sipariş Ürünleri',
            },
        ),
        migrations.CreateModel(
            name='SepetUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toptanci', models.CharField(max_length=80)),
                ('urun_adi', models.CharField(max_length=255)),
                ('marka', models.CharField(blank=True, max_length=100)),
                ('ebat', models.CharField(max_length=30)),
                ('mevsim', models.CharField(blank=True, max_length=20)),
                ('dot', models.CharField(blank=True, max_length=20)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miktar', models.PositiveSmallIntegerField(default=1)),
                ('eklenme', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sepet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sepet Ürünü',
                'verbose_name_plural': 'Sepet Ürünleri',
                'ordering': ['-eklenme'],
            },
        ),
    ]
