# Generated by Django 4.2.16 on 2026-08-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karsilastirma', '0010_siparis_siparisurun_sepeturun'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisurun',
            name='fiyat_ham',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Toptancı ham alış fiyatı', max_digits=10),
        ),
        migrations.AlterField(
            model_name='siparisurun',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, help_text='Kullanıcıya gösterilen fiyat (%10 zam dahil)', max_digits=10),
        ),
    ]
